name: Deploy MCP

on:
  workflow_dispatch:

jobs:
  host-mcp:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Max 6 hours (360 minutes)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install MCP HTTP Bridge dependencies
        working-directory: src/bridge
        run: |
          npm install

      - name: Create required directories
        run: |
          mkdir -p logs tmp
          
      - name: Make install script executable
        run: chmod +x scripts/install-servers.sh

      - name: Install MCP servers
        run: |
          # Set up environment
          export OPENROUTER_API_KEY=${{ secrets.OPENROUTER_TOKEN }}
          
          # Run installation script
          ./scripts/install-servers.sh

      - name: Start MCP HTTP Bridge
        working-directory: src/bridge
        run: |
          # Export environment variables needed by MCP servers
          export OPENROUTER_API_KEY=${{ secrets.OPENROUTER_TOKEN }}
          export GITHUB_SHA=${{ github.sha }}
          export DEPLOYMENT_VERSION="${{ github.sha }}"
          export DEPLOYMENT_TIME="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          
          # Start the bridge server
          echo "Starting MCP HTTP Bridge..."
          echo "Deployment version: ${GITHUB_SHA:0:8}"
          nohup node server.js > bridge.log 2>&1 &
          BRIDGE_PID=$!
          echo "Bridge started with PID: $BRIDGE_PID"
          
          # Wait for bridge to start
          echo "Waiting for bridge to start..."
          for i in {1..30}; do
            if curl -s http://localhost:8080/health > /dev/null 2>&1; then
              echo "✅ MCP HTTP Bridge started successfully"
              
              # List available servers
              echo "Available MCP servers:"
              curl -s http://localhost:8080/servers | jq
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 2
          done
          
          # Verify bridge is running
          if ! curl -s http://localhost:8080/health > /dev/null 2>&1; then
            echo "❌ Failed to start MCP HTTP Bridge"
            echo "Bridge logs:"
            cat bridge.log
            exit 1
          fi

      - name: Set up Cloudflare Tunnel
        uses: AnimMouse/setup-cloudflared@v1

      - name: Start Cloudflare Quick Tunnel
        run: |
          echo "Starting Cloudflare quick tunnel..."
          nohup cloudflared tunnel --no-autoupdate --url http://localhost:8080 > logs/cloudflared.log 2>&1 &
          TUNNEL_PID=$!
          echo "Cloudflare tunnel starting with PID: $TUNNEL_PID"
          
          # Wait for tunnel URL
          echo "Waiting for tunnel URL..."
          for i in {1..30}; do
            if grep -q "https://.*\.trycloudflare\.com" logs/cloudflared.log; then
              echo "✅ Tunnel URL found!"
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 2
          done
          
          # Extract the tunnel URL
          TUNNEL_URL=$(grep -o 'https://[^[:space:]]*\.trycloudflare\.com' logs/cloudflared.log | head -1)
          
          if [ -z "$TUNNEL_URL" ]; then
            echo "❌ Failed to get tunnel URL"
            cat logs/cloudflared.log
            exit 1
          fi
          
          echo "TUNNEL_URL=$TUNNEL_URL" >> $GITHUB_ENV
          echo "✅ Tunnel established at: $TUNNEL_URL"
          
          # Save to file
          echo "$TUNNEL_URL" > tmp/tunnel_url.txt

      - name: Display endpoint info
        run: |
          echo "==================================="
          echo "MCP servers are now accessible at:"
          echo "$TUNNEL_URL"
          echo ""
          echo "Custom domain will be available at:"
          echo "https://mcp.pavlovcik.com"
          echo "(DNS propagation may take a few minutes)"
          echo ""
          echo "Deployment version: ${{ github.sha }}"
          echo "==================================="
          echo ""
          echo "Available endpoints:"
          echo "  Health: $TUNNEL_URL/health"
          echo "  Servers: $TUNNEL_URL/servers"
          echo "  Zen tools: $TUNNEL_URL/servers/zen/tools"
          echo ""
          echo "Via custom domain (after DNS propagates):"
          echo "  Health: https://mcp.pavlovcik.com/health"
          echo "  Servers: https://mcp.pavlovcik.com/servers"
          echo "  Zen tools: https://mcp.pavlovcik.com/servers/zen/tools"
          echo ""
          
          # Save endpoints to file
          cat > tmp/endpoints.txt << EOF
          MCP Server Endpoints:
          Base URL: $TUNNEL_URL
          Health: $TUNNEL_URL/health
          Servers: $TUNNEL_URL/servers
          Zen tools: $TUNNEL_URL/servers/zen/tools
          EOF
          
          # Test the public endpoint
          echo "Testing public endpoint..."
          sleep 5
          
          HEALTH_RESPONSE=$(curl -s --max-time 10 $TUNNEL_URL/health 2>&1 || true)
          
          if echo "$HEALTH_RESPONSE" | jq -e . > /dev/null 2>&1; then
            echo "✅ Public endpoint is working!"
            echo "$HEALTH_RESPONSE" | jq
          else
            echo "❌ Public endpoint test failed!"
            echo "Response:"
            echo "$HEALTH_RESPONSE"
            exit 1
          fi

      - name: Upload tunnel info
        uses: actions/upload-artifact@v4
        with:
          name: tunnel-info
          path: |
            tmp/tunnel_url.txt
            tmp/endpoints.txt
            logs/cloudflared.log

      - name: Update tunnel status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create a simple JSON file with the current tunnel URL
          mkdir -p docs
          cat > docs/tunnel-status.json << EOF
          {
            "url": "$TUNNEL_URL",
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "status": "active",
            "endpoints": {
              "health": "$TUNNEL_URL/health",
              "servers": "$TUNNEL_URL/servers",
              "zen_tools": "$TUNNEL_URL/servers/zen/tools"
            }
          }
          EOF
          
          echo "Tunnel status saved"
          
          # Commit and push to GitHub Pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/tunnel-status.json
          git commit -m "Update tunnel status" || echo "No changes to commit"
          git push || echo "Push failed"

      - name: Update Cloudflare Worker KV
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          echo "Updating Cloudflare Worker KV with tunnel URL..."
          
          # KV namespace ID for MCP_TUNNEL_URL
          KV_NAMESPACE_ID="7e1605c08a3c407c9f8a331f25b5c117"
          
          # Update KV with tunnel URL
          KV_RESPONSE=$(curl -s -X PUT "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/storage/kv/namespaces/$KV_NAMESPACE_ID/values/url" \
            -H "Authorization: Bearer $CF_API_TOKEN" \
            -H "Content-Type: text/plain" \
            --data "$TUNNEL_URL")
          
          echo "✅ Worker KV updated with tunnel URL"
          echo "mcp.pavlovcik.com will now proxy to $TUNNEL_URL"
          echo ""
          echo "Claude Code MCP configuration:"
          echo "URL: https://mcp.pavlovcik.com"

      - name: Keep server running
        run: |
          echo "MCP servers running. Server will auto-shutdown after 1 hour of inactivity..."
          echo "Tunnel URL: $TUNNEL_URL"
          
          # Monitor the bridge process
          BRIDGE_PID=$(pgrep -f "node server.js")
          
          # Keep checking if the process is alive
          while kill -0 $BRIDGE_PID 2>/dev/null; do
            # Check health endpoint to see remaining time
            HEALTH_RESPONSE=$(curl -s http://localhost:8080/health 2>/dev/null || echo "{}")
            if echo "$HEALTH_RESPONSE" | jq -e . > /dev/null 2>&1; then
              REMAINING=$(echo "$HEALTH_RESPONSE" | jq -r '.inactivity.remaining_seconds // 0')
              INACTIVE=$(echo "$HEALTH_RESPONSE" | jq -r '.inactivity.inactive_seconds // 0')
              echo "[$(date)] Server active. Inactive for ${INACTIVE}s, ${REMAINING}s until auto-shutdown"
            fi
            
            sleep 60  # Check every minute
          done
          
          echo "Server has shut down"