name: Host Remote Zen MCP

on:
  workflow_dispatch:

jobs:
  host-mcp:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Max 6 hours (360 minutes)

    steps:
      - name: Checkout repository (optional if no custom code needed)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Clone Zen MCP Server repository
        run: git clone https://github.com/BeehiveInnovations/zen-mcp-server.git

      - name: Install Zen MCP dependencies
        working-directory: zen-mcp-server
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt found; assuming dependencies are handled internally."; fi

      - name: Configure Zen MCP environment
        working-directory: zen-mcp-server
        run: |
          # Configure Zen MCP with OpenRouter API key
          echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_TOKEN }}" >> .env

      - name: Start Zen MCP server in background
        working-directory: zen-mcp-server
        run: |
          source venv/bin/activate
          # Assuming Zen MCP is a FastAPI/uvicorn app; replace with actual start command
          # From docs/community, it's often: uvicorn zen_mcp.server:app --host 0.0.0.0 --port 8080
          nohup uvicorn zen_mcp.server:app --host 0.0.0.0 --port 8080 > mcp.log 2>&1 &
          echo "Waiting for MCP server to start..."
          for i in {1..30}; do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "Zen MCP server started successfully on port 8080"
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 2
          done
          # Check if server is actually running
          if ! curl -s http://localhost:8080 > /dev/null; then
            echo "Failed to start MCP server. Logs:"
            cat mcp.log
            exit 1
          fi

      - name: Set up Cloudflare Tunnel
        uses: AnimMouse/setup-cloudflared@v1
        with:
          cloudflare_tunnel_credential: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}

      - name: Display endpoint info
        run: |
          echo "==================================="
          echo "Zen MCP is now accessible at:"
          echo "https://mcp.pavlovcik.com"
          echo "==================================="
          # Test the public endpoint
          sleep 5
          if curl -s https://mcp.pavlovcik.com > /dev/null 2>&1; then
            echo "✅ Public endpoint is working!"
          else
            echo "⚠️  Public endpoint may still be initializing..."
          fi

      - name: Keep server running for up to 6 hours
        run: |
          # Sleep for 5 hours 50 minutes to stay under 6-hour limit (accounting for startup time)
          sleep 21000
          echo "Server shutting down after timeout"