name: Host Remote Zen MCP

on:
  workflow_dispatch:

jobs:
  host-mcp:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Max 6 hours (360 minutes)

    steps:
      - name: Checkout repository (optional if no custom code needed)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Clone Zen MCP Server repository
        run: git clone https://github.com/BeehiveInnovations/zen-mcp-server.git

      - name: Configure Zen MCP environment
        working-directory: zen-mcp-server
        run: |
          # Configure Zen MCP with OpenRouter API key
          echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_TOKEN }}" > .env

      - name: Make run script executable
        working-directory: zen-mcp-server
        run: chmod +x run-server.sh

      - name: Start Zen MCP server in background
        working-directory: zen-mcp-server
        run: |
          # Use the official run script which handles all setup
          nohup ./run-server.sh > server.log 2>&1 &
          echo "Waiting for MCP server to start..."
          
          # Wait for server to start (it may take time to install dependencies)
          for i in {1..60}; do
            if curl -s http://localhost:3000 > /dev/null 2>&1; then
              echo "✅ Zen MCP server started successfully on port 3000"
              break
            fi
            echo "Waiting... ($i/60)"
            sleep 3
          done
          
          # Check if server is actually running
          if ! curl -s http://localhost:3000 > /dev/null 2>&1; then
            echo "❌ Failed to start MCP server. Logs:"
            cat server.log
            echo "---"
            if [ -f nohup.out ]; then
              echo "Nohup output:"
              cat nohup.out
            fi
            exit 1
          fi

      - name: Set up Cloudflare Tunnel
        uses: AnimMouse/setup-cloudflared@v1
        with:
          cloudflare_tunnel_credential: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}

      - name: Display endpoint info
        run: |
          echo "==================================="
          echo "Zen MCP is now accessible at:"
          echo "https://mcp.pavlovcik.com"
          echo "==================================="
          # Test the public endpoint
          sleep 5
          if curl -s https://mcp.pavlovcik.com > /dev/null 2>&1; then
            echo "✅ Public endpoint is working!"
          else
            echo "⚠️  Public endpoint may still be initializing..."
          fi

      - name: Keep server running for up to 6 hours
        run: |
          # Sleep for 5 hours 50 minutes to stay under 6-hour limit (accounting for startup time)
          sleep 21000
          echo "Server shutting down after timeout"