name: Host Remote MCP Servers

on:
  workflow_dispatch:

jobs:
  host-mcp:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Max 6 hours (360 minutes)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install MCP HTTP Bridge dependencies
        working-directory: mcp-http-bridge
        run: |
          pip install -r requirements.txt

      - name: Make install script executable
        run: chmod +x install-mcp-servers.sh

      - name: Install MCP servers
        run: |
          # Set up environment
          export OPENROUTER_API_KEY=${{ secrets.OPENROUTER_TOKEN }}
          
          # Run installation script
          ./install-mcp-servers.sh

      - name: Start MCP HTTP Bridge
        working-directory: mcp-http-bridge
        run: |
          # Start the bridge server
          echo "Starting MCP HTTP Bridge..."
          nohup python server.py > bridge.log 2>&1 &
          BRIDGE_PID=$!
          echo "Bridge started with PID: $BRIDGE_PID"
          
          # Wait for bridge to start
          echo "Waiting for bridge to start..."
          for i in {1..30}; do
            if curl -s http://localhost:8080/health > /dev/null 2>&1; then
              echo "✅ MCP HTTP Bridge started successfully"
              
              # List available servers
              echo "Available MCP servers:"
              curl -s http://localhost:8080/servers | jq
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 2
          done
          
          # Verify bridge is running
          if ! curl -s http://localhost:8080/health > /dev/null 2>&1; then
            echo "❌ Failed to start MCP HTTP Bridge"
            echo "Bridge logs:"
            cat bridge.log
            exit 1
          fi

      - name: Set up Cloudflare Tunnel
        uses: AnimMouse/setup-cloudflared@v1
        with:
          cloudflare_tunnel_credential: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}

      - name: Display endpoint info
        run: |
          echo "==================================="
          echo "MCP servers are now accessible at:"
          echo "https://mcp.pavlovcik.com"
          echo "==================================="
          echo ""
          echo "Available endpoints:"
          echo "  Health: https://mcp.pavlovcik.com/health"
          echo "  Servers: https://mcp.pavlovcik.com/servers"
          echo "  Zen tools: https://mcp.pavlovcik.com/servers/zen/tools"
          echo ""
          
          # Test the public endpoint
          sleep 5
          if curl -s https://mcp.pavlovcik.com/health > /dev/null 2>&1; then
            echo "✅ Public endpoint is working!"
          else
            echo "⚠️  Public endpoint may still be initializing..."
          fi

      - name: Keep server running
        run: |
          echo "MCP servers running. Will stay active for up to 6 hours..."
          
          # Monitor the bridge process
          BRIDGE_PID=$(pgrep -f "python server.py")
          
          # Sleep for 5 hours 50 minutes, checking every 5 minutes
          for i in {1..70}; do
            if ! kill -0 $BRIDGE_PID 2>/dev/null; then
              echo "⚠️ Bridge process died! Logs:"
              cat mcp-http-bridge/bridge.log
              exit 1
            fi
            echo "[$(date)] Still running... ($(($i * 5)) minutes elapsed)"
            sleep 300  # 5 minutes
          done
          
          echo "Shutting down after timeout"