name: MCP Server Tests

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-mcp:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      timeout-minutes: 5
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: Make test script executable
      timeout-minutes: 1
      run: chmod +x tests/test-mcp.sh

    - name: Check server health before testing
      timeout-minutes: 2
      run: |
        echo "Checking server health..."
        if ! curl --connect-timeout 10 --max-time 30 -f -s https://test.kukapay.com/api/mcp > /dev/null; then
          echo "⚠️  Warning: Default server appears to be down, but continuing with tests"
        else
          echo "✅ Default server is responding"
        fi
        
        if ! curl --connect-timeout 10 --max-time 30 -f -s https://mcp.pavlovcik.com/ > /dev/null; then
          echo "⚠️  Warning: Proxy server appears to be down, but continuing with tests"
        else
          echo "✅ Proxy server is responding"
        fi

    - name: Test MCP server at default endpoint
      timeout-minutes: 3
      run: |
        echo "Starting test of default endpoint..."
        if ! ./tests/test-mcp.sh; then
          echo "❌ Default endpoint test failed"
          exit 1
        fi
      env:
        MCP_URL: https://test.kukapay.com/api/mcp

    - name: Test MCP server at proxy endpoint
      timeout-minutes: 3
      run: |
        echo "Starting test of proxy endpoint..."
        if ! ./tests/test-mcp.sh https://mcp.pavlovcik.com/; then
          echo "❌ Proxy endpoint test failed (continuing anyway)"
        fi
      continue-on-error: true

    - name: Validate test outputs
      timeout-minutes: 1
      run: |
        echo "MCP test completed successfully"
        echo "✅ All endpoints tested"
        echo "Job completed in $(date)"