name: Release Please

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          # Choose release type based on your project
          # Options: node, python, go, rust, simple, etc.
          release-type: simple

          # Ensure tags are prefixed with 'v'
          include-v-in-tag: true

          # Config files in .github folder
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
